- name: Install EPEL repository on CentOS
  ansible.builtin.dnf:
    name: epel-release
    state: present
  become: true


- name: Install tidy html validator
  ansible.builtin.dnf:
    name: tidy
    state: present
    enablerepo: [epel]
