- name: Install and start webserver
  hosts: all
  become: true
  gather_facts: true
  vars:
    string_variable: "Ansible Fast-Track Schulung"
    int_variable: 16
    float_variable: 1.5
    list_variable:
      - Stanki
      - Niko
    dictionary_variable:
      - { skill: Linux, level: 9001 }
      - { skill: Unix, level: 1970 }

  tasks:
    - name: Installiere exakt httpd 2.4.62-5.el9 (x86_64)
      become: true
      ansible.builtin.dnf:
        name: "httpd-2.4.62-5.el9.x86_64"   # NEVRA
        state: present
        allow_downgrade: true

    - name: Collect package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Show httpd version (if installed)
      ansible.builtin.debug:
        msg: "httpd {{ ansible_facts.packages['httpd'][0].version }}-{{ ansible_facts.packages['httpd'][0].release }}
              {{ ansible_facts.packages['httpd'][0].arch }}"
      when: "'httpd' in ansible_facts.packages"

    - name: Not installed
      ansible.builtin.debug:
        msg: "httpd ist nicht installiert"
      when: "'httpd' not in ansible_facts.packages"

    - name: Install-facter command
      ansible.builtin.dnf:
        name: facter
        state: present
        enablerepo: [epel]

    - name: Ensure httpd is running and enabled
      ansible.builtin.service:
        name: httpd          # Debian/Ubuntu: apache2
        state: started
        enabled: true

    - name: Wait for HTTP port
      ansible.builtin.wait_for:
        port: 80
        state: started
        timeout: 10

    - name: Ensure httpd is running and enabled
      ansible.builtin.service:
        name: httpd          # Debian/Ubuntu: apache2
        state: started
        enabled: true
      notify: Restart httpd via handler

    - name: Install httpd for RedHat only
      ansible.builtin.package:
        name: httpd
        state: present
      when: ansible_os_family | lower == "suse"

    - name: Install EPEL repository on CentOS
      ansible.builtin.dnf:
        name: epel-release
        state: present
      become: true


    - name: Install tidy html validator
      ansible.builtin.dnf:
        name: tidy
        state: present
        enablerepo: [epel]

# additional user LAB 7 verbesserung
    - name: Ensure lab users exist
      ansible.builtin.user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        uid: "{{ item.uid }}"
        create_home: true
        shell: /bin/bash
        state: present
      loop:
        - { name: maxm, comment: "Max Mustermann", uid: 1010 }
        - { name: ericam, comment: "Erica Mustermann", uid: 1020 }


# LAB 8
    - name: Copy file to var/www/html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: "0644"

# Lab 9
# retry 8 and change check status
# Lab 10
#    - name: Create sub dir for Max
#      ansible.builtin.shell:
#        cmd: mkdir /var/www/html/dir_max
#        creates: /var/www/html/dir_max
#
#    - name: Create sub dir for Erica
#      ansible.builtin.shell:
#        cmd: mkdir /var/www/html/dir_erica
#        creates: /var/www/html/dir_erica
#
#    - name: Allow access to maxm folder to user Max
#      ansible.builtin.shell: 'chown -R maxm /var/www/html/dir_max'
#
#    - name: Allow access to ericam folder to user Erica
#      ansible.builtin.shell: 'chown -R ericam /var/www/html/dir_erica'

# Lab 10
#    - name: Create sub dir for Max
#      ansible.builtin.shell:
#        cmd: mkdir dir_max
#        creates: dir_max
#      args:
#        chdir: /var/www/html/    #
#
#    - name: Create sub dir for Erica
#      ansible.builtin.shell:
#        cmd: mkdir dir_erica
#        creates: dir_erica
#      args:
#        chdir: /var/www/html/
#
#    - name: Allow access to maxm folder to user Max
#      ansible.builtin.shell: 'chown -R maxm dir_max'
#      args:
#        chdir: /var/www/html/
#
#    - name: Allow access to ericam folder to user Erica
#      ansible.builtin.shell: 'chown -R ericam dir_erica'
#      args:
#        chdir: /var/www/html/


# Lab 10 verbessert
    - name: Set owner on user dirs
      become: true
      ansible.builtin.file:
        path: "/var/www/html/{{ item.dir }}"
        state: directory
        owner: "{{ item.user }}"
        group: "{{ item.user }}"
        mode: "0755"
      loop:
        - { user: maxm, dir: dir_max }
        - { user: ericam, dir: dir_erica }


# Lab 11 Line in file

    - name: "Add Guten Tag to index.html"
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: '<b>guten Tag ;-) !!!</b>'
        regexp: '(?i)\bguten.*$'
        validate: 'grep "guten Tag ;-) !!!" %s'

#    - name: Add Guten Tag to index.html
#      ansible.builtin.lineinfile:
#        path: /var/www/html/index.html
#        line: 'Good Morning'
#       regexp: '^%Guten'
#        insertbefore: body
#        #validate: 'grep "Guten Tag" %s'
#        validate: 'tidy -q -e %s'
#        # validate wird ausgeführt vor dem eigentlichen ändern
#      become: true
#
#    - name: Restart service httpd, in all cases
#      ansible.builtin.service:
#        name: httpd
#        state: restarted

 # Lab 12 Variable definition und chech

    - name: Print my variables
      ansible.builtin.debug:
        msg: "String: {{ string_variable }} Int: {{ int_variable }} Float: {{ float_variable }}
             Liste: {{ list_variable }} Dictionary: {{ dictionary_variable }}"


# Lab 13   Facts in Lineinfile

    - name: Add host information to index.html
      ansible.builtin.lineinfile:
        path: '/var/www/html/index.html'
        line: "{{ ansible_fqdn }} {{ ansible_default_ipv4.address }} {{ ansible_distribution }}"

# Lab 16
#    - name: Copy new content iwth lookup from file
#      ansible.builtin.copy:
#        content: "{{ lookup('file', 'files/pages.html') }}"
#        dest: "/var/www/html/index.html"
#        mode: "0644"

    - name: Show content with uri
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}/index.html   # auf dem Zielhost selbst
        return_content: true
        status_code: [200]
      register: page
      delegate_to: localhost

    - name: Inhalt anzeigen
      ansible.builtin.debug:
        var: page.content

### präferiert

    - name: Show content with command and curl
      ansible.builtin.command:
        argv: ["curl", "-fsS", "http:/{{ inventory_hostname }}/index.html"]
      register: curl_out
      delegate_to: localhost
      changed_when: true

    - name: Inhalt anzeigen
      ansible.builtin.debug:
        var: curl_out.stdout

### Lab 18

    - name: Check cat-facts api
      ansible.builtin.uri:
        url: https://catfact.ninja/fact
        return_content: true
      register: cat_facts

    - name: Print cat_facts
      ansible.builtin.debug:
        msg: "{{ cat_facts.json.fact }}"

    - name: Copy register content
      ansible.builtin.copy:
        content: "{{ cat_facts.json.fact }}"
        dest: "/var/www/html/mypage.html"
        mode: "0644"

  handlers:
    - name: Restart httpd via handler
      ansible.builtin.service:
        name: httpd
        state: restarted
