- name: Install and start webserver
  hosts: test
  become: true
  gather_facts: true
  vars:
    string_variable: "Ansible Fast-Track Schulung"
    int_variable: 16
    float_variable: 1.5
    list_variable:
      - Stanki
      - Niko
    dictionary_variable:
      - { skill: Linux, level: 9001 }
      - { skill: Unix,  level: 1970 }

  tasks:
    - name: Install-httpd
      ansible.builtin.package:
        name: httpd          # Debian/Ubuntu: apache2
        state: latest

    - name: Install-facter command
      ansible.builtin.package:
        name: facter          # Debian/Ubuntu: apache2
        state: latest
        
    - name: Ensure httpd is running and enabled
      ansible.builtin.service:
        name: httpd          # Debian/Ubuntu: apache2
        state: started
        enabled: true

    - name: Wait for HTTP port
      ansible.builtin.wait_for:
        port: 80
        state: started
        timeout: 10

    - name: Ensure httpd is running and enabled
      ansible.builtin.service:
        name: httpd          # Debian/Ubuntu: apache2
        state: started
        enabled: true

    - name: Install EPEL repository on CentOS
      ansible.builtin.yum:
        name: epel-release
        state: present
      become: true


    - name: Install tidy html validator
      ansible.builtin.package:
        name: tidy
        state: latest
      become: true        

# additional user LAB 7 verbesserung
    - name: Ensure lab users exist
      ansible.builtin.user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        uid: "{{ item.uid }}"
        create_home: true
        shell: /bin/bash
        state: present
      loop:
        - { name: maxm,   comment: "Max Mustermann",   uid: 1010 }
        - { name: ericam, comment: "Erica Mustermann", uid: 1020 }


# LAB 8
    - name: Copy file to var/www/html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html

# Lab 9 
# retry 8 and change check status



# Lab 10
#    - name: Create sub dir for Max
#      ansible.builtin.shell:
#        cmd: mkdir /var/www/html/dir_max
#        creates: /var/www/html/dir_max
#
#    - name: Create sub dir for Erica
#      ansible.builtin.shell:
#        cmd: mkdir /var/www/html/dir_erica
#        creates: /var/www/html/dir_erica
#
#    - name: Allow access to maxm folder to user Max
#      ansible.builtin.shell: 'chown -R maxm /var/www/html/dir_max'
#
#    - name: Allow access to ericam folder to user Erica
#      ansible.builtin.shell: 'chown -R ericam /var/www/html/dir_erica'

# Lab 10
#    - name: Create sub dir for Max
#      ansible.builtin.shell:
#        cmd: mkdir dir_max
#        creates: dir_max
#      args:
#        chdir: /var/www/html/        #
#
#    - name: Create sub dir for Erica
#      ansible.builtin.shell:
#        cmd: mkdir dir_erica
#        creates: dir_erica
#      args:
#        chdir: /var/www/html/        
#
#    - name: Allow access to maxm folder to user Max
#      ansible.builtin.shell: 'chown -R maxm dir_max'
#      args:
#        chdir: /var/www/html/
#
#    - name: Allow access to ericam folder to user Erica
#      ansible.builtin.shell: 'chown -R ericam dir_erica'
#      args:
#        chdir: /var/www/html/      


# Lab 10 verbessert
    - name: Set owner on user dirs
      become: true
      ansible.builtin.file:
        path: "/var/www/html/{{ item.dir }}"
        state: directory
        owner: "{{ item.user }}"
        group: "{{ item.user }}"
        mode: "0755"
      loop:
        - { user: maxm,   dir: dir_max }
        - { user: ericam, dir: dir_erica }


# Lab 11 Line in file

    - name: "Add Guten Tag to index.html"
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: '<b>guten Tag ;-) !!!</b>'
        regexp: '(?i)\bguten.*$'
        validate: 'grep "guten Tag ;-) !!!" %s'

#    - name: Add Guten Tag to index.html
#      ansible.builtin.lineinfile:
#        path: /var/www/html/index.html
#        line: 'Good Morning'
#       regexp: '^%Guten'
#        insertbefore: body
#        #validate: 'grep "Guten Tag" %s'
#        validate: 'tidy -q -e %s'
#        # validate wird ausgeführt vor dem eigentlichen ändern
#      become: true        
#
#    - name: Restart service httpd, in all cases
#      ansible.builtin.service:
#        name: httpd
#        state: restarted
 

 # Lab 12 Variable definition und chech

    - name: print my variables
      ansible.builtin.debug:
        msg: "String: {{ string_variable }} Int: {{ int_variable }} Float: {{ float_variable }} Liste: {{ list_variable }} Dictionary: {{ dictionary_variable }}" 


# Lab 13   Facts in Lineinfile      

    - name: Add host information to index.html
      ansible.builtin.lineinfile:
        path: '/var/www/html/index.html'
        line: "{{ ansible_fqdn }} {{ ansible_default_ipv4.address }} {{ ansible_distribution }}"