- name: Modt template teest
  hosts: test
  become: true
  gather_facts: true
  tasks:

    - name: Set /etc/motd from template
      ansible.builtin.template:
        src: "templates/motd.j2"
        dest: "/etc/motd"
        owner: root
        group: root
        mode: "0644"
