- name: Create/Add Users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
  loop: "{{ users }}"

  vars:
    users:
      - name: maxm
        comment: Max Mustermann
        uid: 1010
        password: secure
      - name: ericam
        comment: Erica Musterfrau
        uid: 1011
        password: secure

- name: Create sub dir for Max
  ansible.builtin.command:
    cmd: 'mkdir /var/www/html/dir_max'
    creates: '/var/www/html/dir_max'

- name: Create sub dir for Erica
  ansible.builtin.command:
    cmd: 'mkdir /var/www/html/dir_erica'
    creates: '/var/www/html/dir_erica'

- name: Allow acces to dir_max
  ansible.builtin.command:
    cmd: 'chown -R maxm:maxm /var/www/html/dir_max'

- name: Allow acces to dir_erica
  ansible.builtin.command:
    cmd: 'chown -R ericam:ericam /var/www/html/dir_erica'